In [2]:
import pandas as pd
import glob as glob

In [3]:
geneList = glob.glob("../controls/*/*UQ.txt")
microList = glob.glob("../controls/*/*tion.txt")

In [4]:
geneList

['../controls/TCGA-06-0675/9b571cc1-447f-4fa1-b797-bf95c1ee2372.FPKM-UQ.txt',
 '../controls/TCGA-06-0678/8880fb74-0849-422e-bfd5-4a38c5a0a906.FPKM-UQ.txt',
 '../controls/TCGA-06-0680/d50c9013-3aee-4b1f-be93-225e568da7c3.FPKM-UQ.txt',
 '../controls/TCGA-06-0681/026527d4-007c-4c4e-9bd5-855c44bbe7b0.FPKM-UQ.txt',
 '../controls/TCGA-06-AABW/63a30223-e2e9-45bc-bc42-c00f9202b493.FPKM-UQ.txt']

In [5]:
microList

['../controls/TCGA-06-0675/862f0e7f-e39b-4a11-bdfd-e1f88bfa939a.mirbase21.mirnas.quantification.txt',
 '../controls/TCGA-06-0678/d89ff5eb-6b90-4678-9582-4df71bd558f2.mirbase21.mirnas.quantification.txt',
 '../controls/TCGA-06-0680/d902ff3a-a127-44e4-875e-a606cb5a193d.mirbase21.mirnas.quantification.txt',
 '../controls/TCGA-06-0681/b88b5311-2a20-421b-baf6-c8a3c1799160.mirbase21.mirnas.quantification.txt',
 '../controls/TCGA-06-AABW/67b200bf-3d4f-4da6-98ae-5b00e8f94d8b.mirbase21.mirnas.quantification.txt']

In [6]:
Genes = pd.DataFrame()
Micro = pd.DataFrame()

Genes

Empty DataFrame
Columns: []
Index: []

In [7]:
for el in geneList:
    case = pd.read_csv(el, delimiter='\t', header=None)
    Genes = Genes.append(case.loc[case[0] == 'ENSG00000111653.18'][1], ignore_index=True)
    
case

                        0             1
0       ENSG00000242268.2  2.930076e+03
1       ENSG00000270112.3  3.659016e+03
2      ENSG00000167578.15  2.951175e+05
3       ENSG00000273842.1  0.000000e+00
4       ENSG00000078237.5  6.795730e+04
5      ENSG00000146083.10  2.461691e+05
6       ENSG00000225275.4  0.000000e+00
7      ENSG00000158486.12  0.000000e+00
8      ENSG00000198242.12  1.327294e+06
9       ENSG00000259883.1  0.000000e+00
10      ENSG00000231981.3  1.426854e+03
11      ENSG00000269475.2  0.000000e+00
12      ENSG00000201788.1  0.000000e+00
13     ENSG00000134108.11  1.104315e+06
14      ENSG00000263089.1  3.644628e+02
15     ENSG00000172137.17  1.737700e+05
16      ENSG00000167700.7  2.621839e+05
17      ENSG00000234943.2  1.379545e+03
18      ENSG00000240423.1  6.583398e+03
19      ENSG00000060642.9  1.148746e+05
20      ENSG00000271616.1  0.000000e+00
21      ENSG00000234881.1  0.000000e+00
22      ENSG00000236040.1  5.227019e+02
23      ENSG00000231105.1  2.097977e+02
24      ENSG00000243044.1  0.000000e+00
25      ENSG00000182141.8  1.757765e+05
26      ENSG00000269416.4  3.313670e+03
27      ENSG00000264981.1  0.000000e+00
28      ENSG00000275265.1  0.000000e+00
29      ENSG00000185105.4  1.015632e+04
...                   ...           ...
60453   ENSG00000278151.1  0.000000e+00
60454   ENSG00000228658.1  0.000000e+00
60455   ENSG00000173930.8  6.825307e+02
60456  ENSG00000107863.15  1.160850e+06
60457   ENSG00000199892.2  0.000000e+00
60458   ENSG00000221760.1  0.000000e+00
60459   ENSG00000253333.1  7.009278e+03
60460   ENSG00000213782.6  1.258944e+04
60461  ENSG00000146707.13  1.657240e+05
60462   ENSG00000212084.2  0.000000e+00
60463   ENSG00000248838.2  0.000000e+00
60464   ENSG00000135094.9  2.387631e+04
60465   ENSG00000255083.1  0.000000e+00
60466   ENSG00000223665.1  0.000000e+00
60467   ENSG00000231612.1  1.163509e+03
60468   ENSG00000238300.1  6.420845e+03
60469   ENSG00000267200.1  0.000000e+00
60470   ENSG00000203729.7  0.000000e+00
60471   ENSG00000272515.1  1.566531e+03
60472  ENSG00000009694.12  1.407497e+04
60473   ENSG00000238244.3  0.000000e+00
60474  ENSG00000186115.11  1.655278e+03
60475   ENSG00000216352.1  0.000000e+00
60476   ENSG00000267117.1  5.896694e+03
60477   ENSG00000273233.1  1.220865e+03
60478  ENSG00000105063.17  3.216284e+05
60479   ENSG00000231119.2  7.475013e+03
60480   ENSG00000280861.1  0.000000e+00
60481   ENSG00000123685.7  1.303576e+04
60482   ENSG00000181518.3  0.000000e+00

[60483 rows x 2 columns]

In [8]:
Genes

           14610
0  289290.526839
1  233681.232402
2  305636.137588
3  346971.021483
4  437208.828425

In [9]:
for el in microList:
    case = pd.read_csv(el, delimiter='\t')
    Micro = Micro.append(case.loc[case['miRNA_ID'] == 'hsa-mir-423']['reads_per_million_miRNA_mapped'], ignore_index=True)
    
case

            miRNA_ID  read_count  reads_per_million_miRNA_mapped cross-mapped
0       hsa-let-7a-1       63629                    16030.088569            N
1       hsa-let-7a-2       63440                    15982.473696            Y
2       hsa-let-7a-3       64574                    16268.162933            N
3         hsa-let-7b      119958                    30221.084168            N
4         hsa-let-7c       29711                     7485.108386            Y
5         hsa-let-7d        4729                     1191.379541            N
6         hsa-let-7e       11003                     2771.991773            N
7       hsa-let-7f-1       18722                     4716.643640            N
8       hsa-let-7f-2       18782                     4731.759473            N
9         hsa-let-7g        4968                     1251.590941            N
10        hsa-let-7i        1860                      468.590811            N
11       hsa-mir-100      150716                    37969.963833            N
12     hsa-mir-101-1       31483                     7931.529309            N
13     hsa-mir-101-2       31459                     7925.482976            N
14    hsa-mir-103a-1       90519                    22804.500890            Y
15    hsa-mir-103a-2       90955                    22914.342607            Y
16    hsa-mir-103b-1           0                        0.000000            N
17    hsa-mir-103b-2           0                        0.000000            N
18     hsa-mir-105-1         231                       58.195956            N
19     hsa-mir-105-2         237                       59.707539            N
20      hsa-mir-106a          90                       22.673749            Y
21      hsa-mir-106b        1726                      434.832119            N
22       hsa-mir-107         496                      124.957550            Y
23       hsa-mir-10a         303                       76.334955            N
24       hsa-mir-10b         332                       83.640941            N
25       hsa-mir-1-1          19                        4.786680            N
26      hsa-mir-1178           0                        0.000000            N
27      hsa-mir-1179           8                        2.015444            N
28      hsa-mir-1180         530                      133.523188            N
29      hsa-mir-1181           1                        0.251931            N
...              ...         ...                             ...          ...
1851     hsa-mir-921           0                        0.000000            N
1852     hsa-mir-922           0                        0.000000            N
1853     hsa-mir-924           0                        0.000000            N
1854   hsa-mir-92a-1       25500                     6424.228866            N
1855   hsa-mir-92a-2       23411                     5897.945960            N
1856     hsa-mir-92b        2466                      621.260721            N
1857      hsa-mir-93       14537                     3662.314315            N
1858     hsa-mir-9-3      338227                    85209.712023            N
1859     hsa-mir-933           0                        0.000000            N
1860     hsa-mir-934           0                        0.000000            N
1861     hsa-mir-935         473                      119.163147            N
1862     hsa-mir-936           0                        0.000000            N
1863     hsa-mir-937          16                        4.030889            N
1864     hsa-mir-938           0                        0.000000            N
1865     hsa-mir-939           0                        0.000000            N
1866     hsa-mir-940          25                        6.298264            N
1867   hsa-mir-941-1           0                        0.000000            N
1868   hsa-mir-941-2           0                        0.000000            N
1869   hsa-mir-941-3           0                        0.000000            N
1870   hsa-mir-941-4           0                        0.000000            N
1871   hsa-mir-941-5           0                        0.000000            N
1872     hsa-mir-942          28                        7.054055            N
1873     hsa-mir-943           0                        0.000000            N
1874     hsa-mir-944           0                        0.000000            N
1875      hsa-mir-95          80                       20.154444            N
1876    hsa-mir-9500           0                        0.000000            N
1877      hsa-mir-96           0                        0.000000            N
1878      hsa-mir-98         684                      172.320492            N
1879     hsa-mir-99a        8007                     2017.207864            N
1880     hsa-mir-99b      268762                    67709.356801            N

[1881 rows x 4 columns]

In [10]:
Micro

          671
0  126.830687
1  147.548693
2  146.724218
3  171.776358
4  223.714323

In [11]:
Genes.columns = ['exprG']
Micro.columns = ['exprM']

In [12]:
Genes

           exprG
0  289290.526839
1  233681.232402
2  305636.137588
3  346971.021483
4  437208.828425

In [13]:
Micro

        exprM
0  126.830687
1  147.548693
2  146.724218
3  171.776358
4  223.714323

In [14]:
ds = pd.concat([Genes, Micro], axis = 1)

In [15]:
ds

           exprG       exprM
0  289290.526839  126.830687
1  233681.232402  147.548693
2  305636.137588  146.724218
3  346971.021483  171.776358
4  437208.828425  223.714323

In [16]:
ds.to_csv('controlDataset')

In [17]:
pwd

u'/media/empro/5C02C2EB02C2C8EA/Ubuntu/medBiost/firstTask/data/lowerGradeBliastoma/genesMicro/dataManip'